name: "⚠️ Bug"
description: "버그/오류 리포트"
labels: ["bug"]
title: "[BUG] "

body:
  - type: textarea
    attributes:
      label: ❗️ 문제 사항
      description: 발생한 문제 상황을 구체적으로 기록해 주세요. 캡쳐 화면이나 로그도 함께 첨부해 주시면 좋습니다.
      placeholder: |
        반드시 -, 1. 2. 등의 글머리 기호를 통해 구분하여 주세요.
        이미지는 항상 해당 내용의 하단에 첨부합니다.
        작성 예시
        1. 로그인 버튼 클릭 시 페이지가 무한 로딩
        <이미지>

        2. 특정 브라우저(IE 11)에서 UI가 깨짐
        <이미지>

  - type: textarea
    attributes:
      label: 📝 재현 절차
      description: 해당 버그를 재현할 수 있는 단계(step)를 기록해 주세요.
      placeholder: |
        반드시 -, 1. 2. 등의 글머리 기호를 통해 구분하여 주세요.
        이미지는 항상 해당 내용의 하단에 첨부합니다.
        작성 예시
        1. 로그인 페이지 접속
        2. 올바른 아이디/비밀번호 입력
        3. 로그인 버튼 클릭
        4. 무한 로딩 발생 확인

  - type: textarea
    attributes:
      label: ✅ 기대 동작
      description: 정상적으로 동작했을 경우 기대되는 결과를 기록해 주세요.
      placeholder: |
        반드시 -, 1. 2. 등의 글머리 기호를 통해 구분하여 주세요.
        이미지는 항상 해당 내용의 하단에 첨부합니다.
        작성 예시
        - 로그인 성공 시 메인 페이지로 이동해야 함

  - type: textarea
    attributes:
      label: 📄 환경 정보
      description: 문제가 발생한 환경을 기록해 주세요. (OS/디바이스/브라우저 등)
      placeholder: |
        반드시 -, 1. 2. 등의 글머리 기호를 통해 구분하여 주세요.
        이미지는 항상 해당 내용의 하단에 첨부합니다.
        작성 예시
        - Device: MacBook Pro 16-inch
        - OS: macOS Sonoma 14.5
        - Browser: Chrome 126.0
        - Node.js: 20.11.1
        - npm: 10.5.2

  - type: textarea
    attributes:
      label: 📂 참고 자료
      description: 참고할 만한 로그, 링크, 관련 문서가 있다면 첨부해 주세요. 없으면 `> N/A` 그대로 두시면 됩니다.
      placeholder: |
        작성 예시
        > https://example.com/error-log
        혹은 > 를 지우고 이미지 첨부
      value: "> N/A"
