name: "🐛 Bug Report"
description: "버그가 발생했을 때 작성하는 이슈 템플릿"
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "## 🌐 실행 환경"
  - type: input
    id: environment
    attributes:
      label: "## 환경 정보"
      placeholder: "예: Chrome 128 / macOS / Node 20"

  - type: markdown
    attributes:
      value: "## 🐞 버그 설명"
  - type: textarea
    id: description
    attributes:
      label: "내용"
      placeholder: "어떤 상황에서 어떤 오류가 났는지..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🔁 재현 방법"
  - type: textarea
    id: steps
    attributes:
      label: "Steps"
      placeholder: |
        1. 로그인 페이지 접속
        2. 비밀번호 입력
        3. 로그인 버튼 클릭
        4. 에러 발생
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ✅ 예상 결과"
  - type: textarea
    id: expected
    attributes:
      label: "Expected"
      placeholder: "예: 정상적으로 로그인 화면으로 이동해야 함"
