name: "âœ¨ Feature"
description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: ðŸ”§ ìž‘ì—… ë‚´ìš©
      description: ìž‘ì—… ë‚´ìš©ì„ ê¸°ë¡í•´ ì£¼ì„¸ìš”. í•„ìš”í•œ ê²½ìš° ì´ë¯¸ì§€ë‚˜ ìŠ¤í¬ë¦°ìƒ·ì„ í•¨ê»˜ ì²¨ë¶€í•´ ì£¼ì„¸ìš”.
      placeholder: |
        ë°˜ë“œì‹œ -, 1. 2. ë“±ì˜ ê¸€ë¨¸ë¦¬ ê¸°í˜¸ë¥¼ í†µí•´ êµ¬ë¶„í•˜ì—¬ ì£¼ì„¸ìš”.
        ìž‘ì„± ì˜ˆì‹œ
        1. ë¡œê·¸ì¸ ê¸°ëŠ¥ êµ¬í˜„
        - ë¡œê·¸ì¸ ì„±ê³µ ì‹œ í† í° ì €ìž¥
        - ì‹¤íŒ¨ ì‹œ ì—ëŸ¬ ë©”ì‹œì§€ ì¶œë ¥
        2. UI ê°œì„ 
        - ë¡œê·¸ì¸ ë²„íŠ¼ ìƒ‰ìƒ ë³€ê²½
        - ë°˜ì‘í˜• ì„¤ê³„
        ...

  - type: textarea
    attributes:
      label: ðŸ“„ ì˜ì¡´ì„± ì¶”ê°€/ë³€ê²½ ì‚¬í•­
      description: ì¶”ê°€/ë³€ê²½/ì‚­ì œëœ ì˜ì¡´ì„±ì„ ë²„ì „ê³¼ í•¨ê»˜ ê¸°ë¡í•´ ì£¼ì„¸ìš”. ì—†ìœ¼ë©´ `N/A` ê·¸ëŒ€ë¡œ ë‘ì‹œë©´ ë©ë‹ˆë‹¤.
      placeholder: |
        ë°˜ë“œì‹œ -, 1. 2. ë“±ì˜ ê¸€ë¨¸ë¦¬ ê¸°í˜¸ë¥¼ í†µí•´ êµ¬ë¶„í•˜ì—¬ ì£¼ì„¸ìš”.
        ìž‘ì„± ì˜ˆì‹œ
        1. axios@1.7.2 ì¶”ê°€
        2. react-query@5.0.0 -> 5.1.0 ë²„ì „ ì—…ê·¸ë ˆì´ë“œ
        3. lodash ì œê±°
      value: N/A

  - type: textarea
    attributes:
      label: ðŸ“‚ ì°¸ê³  ìžë£Œ
      description: ì°¸ê³ í•œ ë¬¸ì„œì˜ ë§í¬ë‚˜ ì´ë¯¸ì§€ê°€ ìžˆë‹¤ë©´ ì²¨ë¶€í•´ ì£¼ì„¸ìš”. ì—†ìœ¼ë©´ `> N/A` ê·¸ëŒ€ë¡œ ë‘ì‹œë©´ ë©ë‹ˆë‹¤.
      placeholder: |
        > https://example.com/design-doc
        í˜¹ì€ ì´ë¯¸ì§€ ì²¨ë¶€
      value: "> N/A"
